export const actionType = {
  FETCH_MOVIES: "FETCH_MOVIES",
  SELECT_MOVIES: "SELECT_MOVIES",
  REMOVE_SELECTED_MOVIES: "REMOVE_SELECTED_MOVIES",
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
};  
